#ifndef RESOURCES_H_INCLUDED
#define RESOURCES_H_INCLUDED

#define DEFAULT_STATIC		101
#define DEFAULT_BUTTON		102
#define DEFAULT_EDIT		103

#define ENHANCED_BUTTON		201
#define ENHANCED_STATIC		202
#define ENHANCED_EDIT		203

#endif // RESOURCES_H_INCLUDED